version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: daily
      time: "04:00"
    labels:
      - dependencies
      - CJS
    target-branch: master
    open-pull-requests-limit: 10
    ignore:
      - dependency-name: "@types/node"
        update-types: [ "version-update:semver-patch" ]
      - dependency-name: mocha
        versions:
          - "10.x"
      # Ignore ESM version
      - dependency-name: got
        versions:
          - ">=12.x"
